"use client";

import React, { useRef, useState, useEffect } from "react";
import { Payslip } from "@/types";
import { formatCurrency, formatDate } from "@/lib/utils";
import { payrollApi } from "@/lib/api";
import {
  Printer,
  Download,
  X,
  Building2,
  ShieldCheck,
  QrCode,
  CheckCircle2,
  Clock,
  Loader2,
} from "lucide-react";

interface PayslipModalProps {
  payslip: Payslip | null;
  isOpen: boolean;
  onClose: () => void;
}

export default function PayslipModal({ payslip, isOpen, onClose }: PayslipModalProps) {
  const printRef = useRef<HTMLDivElement>(null);
  const [details, setDetails] = useState<any>(null);
  const [loadingDetails, setLoadingDetails] = useState(false);

  useEffect(() => {
    async function loadFullDetails() {
      if (!isOpen || !payslip) return;
      setLoadingDetails(true);
      try {
        const res = await payrollApi.getPayslipDetails(payslip.id);
        if (res?.success && res.data) {
          setDetails(res.data);
        } else {
          setDetails(null);
        }
      } catch {
        setDetails(null);
      } finally {
        setLoadingDetails(false);
      }
    }
    loadFullDetails();
  }, [isOpen, payslip]);

  if (!isOpen || !payslip) return null;

  const handlePrint = () => {
    window.print();
  };

  const monthNames = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];
  const monthString = monthNames[payslip.month - 1] || `Month ${payslip.month}`;

  // Company and Template overrides
  const template = details?.template || null;
  const companyName =
    details?.organization?.name ||
    template?.companyName ||
    (payslip as any).organization?.name ||
    "Enterprise Organization";

  const companyAddress =
    details?.organization?.address ||
    (template?.addressLine1 ? `${template.addressLine1}${template.addressLine2 ? ", " + template.addressLine2 : ""}` : "") ||
    "Corporate Headquarters, Cyber City, Phase II";

  const logoUrl = details?.organization?.logoUrl || template?.logoUrl || "/logo.png";
  const taxLabel = details?.organization?.taxIdentifierLabel || template?.taxIdentifierLabel || "CIN / GSTIN";
  const taxValue = details?.organization?.taxIdentifierValue || template?.taxIdentifierValue || "";
  const primaryColor = template?.primaryColor || "#4f46e5";
  const headerLayout = template?.headerLayout || "SPLIT";

  // Section Visibility Toggles (default true if not configured)
  const showBank = template?.showBankDetails ?? true;
  const showPan = template?.showPanUan ?? true;
  const showAttendance = template?.showAttendanceSummary ?? true;
  const showLeave = template?.showLeaveBalances ?? true;
  const showOvertime = template?.showOvertimeDetails ?? true;
  const showWords = template?.showNetSalaryInWords ?? true;
  const showQr = template?.showBarcodeOrQr ?? true;

  const signatoryName = template?.signatoryName || "Authorized Signatory";
  const signatoryTitle = template?.signatoryTitle || "Head of Human Resources & Finance";
  const signatureImageUrl = template?.signatureImageUrl || null;
  const declarationText =
    template?.declarationText ||
    "This is an electronically verified payslip generated by WorkPulse HRMS. No physical signature is required.";

  // Safe fallback numbers
  const basicSalary = Number(payslip.basicSalary || (payslip as any).baseSalary || 0);
  const hra = Number(payslip.hra || 0);
  const allowances = Number(payslip.allowances || (payslip as any).allowancesTotal || 0);
  const overtimePay = Number(payslip.overtimePay || 0);
  const grossSalary = Number(payslip.grossSalary || (basicSalary + hra + allowances + overtimePay));
  const totalDeductions = Number(payslip.totalDeductions || (payslip as any).deductionsTotal || 0);
  const netSalary = Number(payslip.netSalary || 0);
  const lopDeduction = Number((payslip as any).lopDeduction || (payslip as any).unpaidLeaveDeduction || 0);

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
      <div className="w-full max-w-3xl bg-white text-slate-900 rounded-3xl p-6 sm:p-10 shadow-2xl relative my-8 print:p-0 print:m-0 print:shadow-none print:w-full print:max-w-none">
        {/* Top Control Bar (Hidden on print) */}
        <div className="flex items-center justify-between pb-6 border-b border-slate-200 mb-6 print:hidden">
          <div className="flex items-center gap-2">
            <span
              className="px-3 py-1 rounded-full text-xs font-bold border"
              style={{ backgroundColor: `${primaryColor}15`, color: primaryColor, borderColor: `${primaryColor}30` }}
            >
              Payslip #{details?.referenceNo || payslip.id.slice(0, 8).toUpperCase()}
            </span>
            <span
              className={`px-2.5 py-0.5 rounded-full text-xs font-semibold ${
                payslip.status === "PAID" || (payslip.status as string) === "DISBURSED"
                  ? "bg-emerald-50 text-emerald-700"
                  : "bg-amber-50 text-amber-700"
              }`}
            >
              {payslip.status}
            </span>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handlePrint}
              className="px-3.5 py-2 rounded-xl text-white font-semibold text-xs flex items-center gap-2 shadow-sm transition hover:opacity-90"
              style={{ backgroundColor: primaryColor }}
            >
              <Printer className="w-4 h-4 text-white" />
              <span>Print / Save PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-xl text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Payslip Letterhead Document */}
        <div ref={printRef} className="space-y-6 text-slate-800">
          {/* 1. Header rendered based on Company Template headerLayout */}
          {headerLayout === "BANNER" ? (
            <div
              className="p-6 rounded-2xl text-white flex items-center justify-between shadow-sm"
              style={{ backgroundColor: primaryColor }}
            >
              <div className="flex items-center gap-3">
                {logoUrl && (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img src={logoUrl} alt="Logo" className="w-12 h-12 object-contain bg-white rounded-xl p-1 shrink-0" />
                )}
                <div>
                  <h2 className="text-xl font-black tracking-tight">{companyName}</h2>
                  <p className="text-xs text-white/80">{companyAddress}</p>
                </div>
              </div>
              <div className="text-right">
                <span className="px-2.5 py-0.5 rounded text-[10px] font-extrabold bg-white/20 uppercase tracking-wider block mb-0.5">
                  Salary Payslip
                </span>
                <span className="text-xs font-bold">{monthString} {payslip.year}</span>
              </div>
            </div>
          ) : headerLayout === "CENTERED" ? (
            <div className="text-center pb-6 border-b-2" style={{ borderColor: primaryColor }}>
              {logoUrl && (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={logoUrl} alt="Logo" className="w-12 h-12 object-contain mx-auto mb-2" />
              )}
              <h2 className="text-xl font-black text-slate-900 tracking-tight">{companyName}</h2>
              <p className="text-xs text-slate-500 mt-0.5">{companyAddress}</p>
              <p className="text-[10px] text-slate-400 mt-0.5">
                {taxLabel}: <span className="font-semibold text-slate-600">{taxValue}</span>
              </p>
              <div
                className="inline-flex items-center gap-2 mt-2 px-3 py-0.5 rounded-full text-[11px] font-bold text-white"
                style={{ backgroundColor: primaryColor }}
              >
                <span>Payslip for {monthString} {payslip.year}</span>
              </div>
            </div>
          ) : (
            /* SPLIT DUAL LAYOUT */
            <div className="flex items-start justify-between pb-6 border-b-2" style={{ borderColor: primaryColor }}>
              <div>
                <div className="flex items-center gap-2.5">
                  <div className="w-10 h-10 rounded-xl overflow-hidden shrink-0 shadow-xs border border-slate-200 p-0.5 flex items-center justify-center bg-white">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src={logoUrl} alt="Company Logo" className="max-w-full max-h-full object-contain" />
                  </div>
                  <div>
                    <h2 className="text-xl font-black tracking-tight text-slate-900">{companyName}</h2>
                    <p className="text-xs text-slate-500">{companyAddress}</p>
                  </div>
                </div>
                <p className="text-[10px] text-slate-400 mt-1">
                  {taxLabel}: <span className="font-semibold text-slate-600">{taxValue}</span>
                </p>
              </div>

              <div className="text-right">
                <h3 className="text-base font-black text-slate-900 uppercase tracking-wide">
                  Salary Payslip
                </h3>
                <p className="text-xs font-bold" style={{ color: primaryColor }}>
                  {monthString} {payslip.year}
                </p>
                <p className="text-[11px] text-slate-400 mt-1">
                  Generated: {formatDate(payslip.createdAt)}
                </p>
              </div>
            </div>
          )}

          {/* 2. Employee Information Grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 rounded-2xl bg-slate-50 border border-slate-200 text-xs">
            <div>
              <span className="text-slate-400 block text-[10px] uppercase font-bold">Employee Name</span>
              <span className="font-bold text-slate-900 text-sm">
                {details?.employee?.name || `${payslip.employee?.firstName} ${payslip.employee?.lastName || ""}`}
              </span>
            </div>
            <div>
              <span className="text-slate-400 block text-[10px] uppercase font-bold">Employee Code</span>
              <span className="font-bold text-slate-900">
                {details?.employee?.employeeCode || payslip.employee?.employeeCode || "WP-EMP-001"}
              </span>
            </div>
            <div>
              <span className="text-slate-400 block text-[10px] uppercase font-bold">Designation</span>
              <span className="font-bold text-slate-900">
                {details?.employee?.designation || (payslip.employee as any)?.designation || "Staff Professional"}
              </span>
            </div>
            <div>
              <span className="text-slate-400 block text-[10px] uppercase font-bold">Department</span>
              <span className="font-bold text-slate-900">
                {details?.employee?.department || payslip.employee?.department?.name || "General Operations"}
              </span>
            </div>

            {showBank && (
              <>
                <div>
                  <span className="text-slate-400 block text-[10px] uppercase font-bold">Bank Name</span>
                  <span className="font-bold text-slate-900">
                    {details?.employee?.bankName || "HDFC Bank Ltd."}
                  </span>
                </div>
                <div>
                  <span className="text-slate-400 block text-[10px] uppercase font-bold">Account Number</span>
                  <span className="font-bold text-slate-900">
                    {details?.employee?.accountNumber || "••••••••4892"}
                  </span>
                </div>
              </>
            )}

            {showPan && (
              <>
                <div>
                  <span className="text-slate-400 block text-[10px] uppercase font-bold">PAN Number</span>
                  <span className="font-bold text-slate-900">{details?.employee?.panNumber || "ABCDE1234F"}</span>
                </div>
                <div>
                  <span className="text-slate-400 block text-[10px] uppercase font-bold">Branch</span>
                  <span className="font-bold text-slate-900">
                    {details?.employee?.branch || payslip.employee?.branch?.name || "Main Campus"}
                  </span>
                </div>
              </>
            )}
          </div>

          {/* 3. Attendance Summary (if enabled) */}
          {showAttendance && (
            <div className="grid grid-cols-4 sm:grid-cols-5 gap-2 text-center p-3 rounded-xl border border-slate-200 text-xs bg-white">
              <div>
                <span className="text-[10px] text-slate-400 block">Total Days</span>
                <span className="font-extrabold text-slate-900">
                  {details?.attendance?.workingDays || (payslip as any).workingDays || 26}
                </span>
              </div>
              <div>
                <span className="text-[10px] text-slate-400 block">Present</span>
                <span className="font-extrabold text-emerald-600">
                  {details?.attendance?.presentDays !== undefined ? details.attendance.presentDays : Number((payslip as any).presentDays || 0)}
                </span>
              </div>
              <div>
                <span className="text-[10px] text-slate-400 block">Paid Leave</span>
                <span className="font-extrabold text-indigo-600">
                  {details?.attendance?.paidLeaveDays !== undefined ? details.attendance.paidLeaveDays : Number((payslip as any).paidLeaveDays || 0)}
                </span>
              </div>
              <div>
                <span className="text-[10px] text-slate-400 block">Loss of Pay</span>
                <span className="font-extrabold text-rose-600">
                  {details?.attendance?.unpaidLeaveDays !== undefined ? details.attendance.unpaidLeaveDays : Number((payslip as any).unpaidLeaveDays || 0)}
                </span>
              </div>
              {showOvertime && (
                <div>
                  <span className="text-[10px] text-slate-400 block">Overtime</span>
                  <span className="font-extrabold" style={{ color: primaryColor }}>
                    {details?.attendance?.overtimeHours !== undefined ? details.attendance.overtimeHours : Number((payslip as any).overtimeHours || 0)} hrs
                  </span>
                </div>
              )}
            </div>
          )}

          {/* 4. Earnings & Deductions Breakdown Table */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {/* Earnings Column */}
            <div className="border border-slate-200 rounded-2xl overflow-hidden">
              <div
                className="px-4 py-2.5 font-bold text-xs uppercase tracking-wide border-b border-slate-200 flex justify-between"
                style={{ backgroundColor: `${primaryColor}10`, color: primaryColor }}
              >
                <span>Earnings</span>
                <span>Amount (INR)</span>
              </div>
              <div className="p-4 space-y-2.5 text-xs">
                <div className="flex justify-between">
                  <span className="text-slate-600">Basic Salary</span>
                  <span className="font-semibold">{formatCurrency(basicSalary)}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-600">House Rent Allowance (HRA)</span>
                  <span className="font-semibold">{formatCurrency(hra)}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-600">Special & Other Allowances</span>
                  <span className="font-semibold">{formatCurrency(allowances)}</span>
                </div>
                {overtimePay > 0 && showOvertime && (
                  <div className="flex justify-between text-emerald-600 font-semibold">
                    <span>Overtime Pay (OT)</span>
                    <span>+{formatCurrency(overtimePay)}</span>
                  </div>
                )}
                <div className="pt-3 border-t border-slate-200 flex justify-between font-bold text-sm text-slate-900">
                  <span>Gross Earnings</span>
                  <span style={{ color: primaryColor }}>{formatCurrency(grossSalary)}</span>
                </div>
              </div>
            </div>

            {/* Deductions Column */}
            <div className="border border-slate-200 rounded-2xl overflow-hidden">
              <div className="bg-slate-100 px-4 py-2.5 font-bold text-xs text-slate-800 uppercase tracking-wide border-b border-slate-200 flex justify-between">
                <span>Statutory Deductions</span>
                <span>Amount (INR)</span>
              </div>
              <div className="p-4 space-y-2.5 text-xs">
                <div className="flex justify-between">
                  <span className="text-slate-600">Provident Fund (PF)</span>
                  <span className="font-semibold">
                    {formatCurrency(Number((payslip as any).pfDeduction || Math.round(basicSalary * 0.12)))}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-600">Employee State Insurance (ESI)</span>
                  <span className="font-semibold">{formatCurrency(Number((payslip as any).esiDeduction || 0))}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-600">Professional Tax (PT)</span>
                  <span className="font-semibold">{formatCurrency(Number((payslip as any).ptDeduction || 200))}</span>
                </div>
                {lopDeduction > 0 && (
                  <div className="flex justify-between text-rose-600 font-semibold">
                    <span>Loss of Pay (Absent / LOP)</span>
                    <span>-{formatCurrency(lopDeduction)}</span>
                  </div>
                )}
                <div className="pt-3 border-t border-slate-200 flex justify-between font-bold text-sm text-slate-900">
                  <span>Total Deductions</span>
                  <span className="text-rose-600">{formatCurrency(totalDeductions)}</span>
                </div>
              </div>
            </div>
          </div>

          {/* 5. Net Salary Take-Home Banner */}
          <div
            className="p-5 rounded-2xl text-white flex flex-wrap items-center justify-between gap-4 shadow-sm"
            style={{ backgroundColor: primaryColor }}
          >
            <div>
              <span className="text-xs font-bold text-white/80 uppercase tracking-wide block">
                Net Take-Home Disbursed Pay
              </span>
              <p className="text-2xl font-black">{formatCurrency(netSalary)}</p>
              {showWords && details?.netSalaryWords && (
                <p className="text-[11px] text-white/90 italic mt-0.5">{details.netSalaryWords}</p>
              )}
            </div>

            {showQr && (
              <div className="flex items-center gap-2 bg-white/10 px-3 py-1.5 rounded-xl text-[10px] font-mono">
                <QrCode className="w-5 h-5 text-white" />
                <span>AUTHENTICATED • ID {payslip.id.slice(-8).toUpperCase()}</span>
              </div>
            )}
          </div>

          {/* 6. Footer, Declaration & Authorized Signatory */}
          <div className="pt-8 border-t border-slate-200 flex items-end justify-between text-xs text-slate-500">
            <div className="max-w-sm space-y-1">
              <p className="font-semibold text-slate-800">Compliance & Authenticity Notice:</p>
              <p className="text-[11px] leading-relaxed">{declarationText}</p>
            </div>

            <div className="text-right space-y-1">
              {signatureImageUrl && (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={signatureImageUrl} alt="Signature Stamp" className="h-10 object-contain ml-auto" />
              )}
              <div className="w-36 border-t border-slate-400 mt-2 pt-1">
                <span className="text-[11px] font-bold text-slate-800 block">{signatoryName}</span>
                <p className="text-[10px] text-slate-400">{signatoryTitle}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
